### PR TITLE
I announced that I don't want to take care of IIS.

### PR DESCRIPTION
**Pull request by piwikjapan**
In short, the customers are very interested in your program.

### CODE REVIEW

**Comment by dugwood** [comment]
Thanks. IIS was some pain in the a*\* to dealt with.

**Comment by piwikjapan** [comment]
Unbelievable that such an important system is operated on IIS. 
But maybe they just obey the plan of employment. 
So I  say softly, why you are using IIS ?

**Comment by dugwood** [comment]
I don't use it myself, always run under Linux. But IIS was using CGI for PHP support, so IIRC it was just a few hacks (and the backslashes instead of slashes, but I think that PHP handles it natively).

Does piwik support IIS?

**Comment by piwikjapan** [comment]
Yes, and I heard somewhere a big company in Japan wants to use Piwik on Windows. Microsoft sells Windows very cheaper than Redhat for large companies and governments.

**Pull request merged**
