### PR TITLE
Added another language files.

### PR DESCRIPTION
**Pull request by selfnavi**
A css file was modified.
Added choice “google chrome” browser.

I will put this plugin on Piwik Plugins Marketplace.

### CODE REVIEW

**Comment by dugwood** [comment]
Thanks. I'll try to add some links on dugwood.com to direct download of the piwik plugin.

**Comment by selfnavi** [comment]
I was very surprised that everyone in the world still tell their opinions on your ClickHeat plugin, but anyone does not help you.

**Comment by selfnavi** [comment]
I was very surprised that everyone in the world still tell their opinions on your ClickHeat plugin, but anyone does not help you.

**Comment by dugwood** [comment]
Where are these opinions? I was following the old Trac website of Piwik, but I didn't track the new forum/tool.

Also, I must say that I didn't want to spend so much time on this plugin, as basically ClickHeat is standalone. Anyway, I didn't have enough time to launch ClickHeat 2.0, with database support, that would have worked well along side with Piwik, but not as a Piwik plugin.

So thanks for your time and help, really. As I don't use Piwik, I just did what was needed for it to work on the previous release.

**Comment by selfnavi** [comment]
Here's a link: https://github.com/piwik/piwik/issues/6371
And even in Japan, I heard that ClickHeat plugin issued for Piwik 1.x, but it does not work on 2.x.
> as basically ClickHeat is standalone
But it works well on Piwik.

**Comment by selfnavi** [comment]
Here's a link: https://github.com/piwik/piwik/issues/6371
And even in Japan, I heard that ClickHeat plugin issued for Piwik 1.x, but it does not work on 2.x.

> as basically ClickHeat is standalone

But it works well on Piwik.

**Comment by dugwood** [comment]
Standalone, but at some point I've built a plugin for Piwik. That's all the files you've been updating so far.

I must admit that I have no time or desire to redesign the whole application only for Piwik. It was a thought a while ago, not creating ClickHeat 2.0, but instead release it under «Piwik Heatmap».

If someone wants a better implementation, I'll be happy to help, but I don't want to build it myself. Also I'm really pleased that ClickHeat helped a lot of people, and that a lot of forks or similar projects exist, including the Piwik (soon to be) Heatmap plugin.

Maybe, with HTML5 and the like, better software and CPU, Piwik can achieve a better plugin, with parts of ClickHeat and the other open-sourced software.

So if it's easy to make it work on Piwik 2.x, thanks for the work on this, in the name of all the future users. Else you may look towards the future code that arises from the https://github.com/piwik/piwik/issues/6371 thread.

**Comment by dugwood** [comment]
See https://github.com/piwik/piwik/issues/5493 for instance, that was where I helped (originally on a Trac website)

**Comment by selfnavi** [comment]
Of course I know. I have read carefully. And you have no time too, I know. 
In any case, your program is unique in OSS, first I want to show ClickHeat widely in Japan on confarence for OSS. 
Thank you for your good programs.

**Comment by dugwood** [comment]
I'm honored :-) ClickHeat was designed in a few hours, after I tried a paid, closed source script that did the same thing. Then one of friends told me: why don't you release it, as OSS? And that was the start of it.
I didn't have much time since then to create more OSS, but I eager too. I've helped https://github.com/phalcon/cphalcon/ a little bit, because I started working with this, and Zephir is very promising for PHP software.

**Comment by selfnavi** [comment]
> ClickHeat was designed in a few hours

In short, your friends said that you have a talent for the OSS, and why not want to show ? Yes, I agree.
Few hours ? It's not a matter of time. You have good ideas and technology.

Now I'm taking screenshots ClickHeat for Piwik marketplace. Piwik macketplace require special repository to show own plugin, so I did.
Please see this link: https://github.com/piwikjapan/plugin-clickheat

**Comment by dugwood** [comment]
No, he said that I should release it because it would be valuable for many people. It took me a lot of my time (bugfixing, support & so on), but that was a good experience.

I'm glad you released your own version of plugin, I can link to it.

Just a note on «Does it withstands high traffics ? Unfortunately not. Because this plugin uses text files to record data. Therefore, please use this plugin to experiment or low traffics.»
To me, you're wrong. File based logging is far more efficient that a default database setting. It's just appending data. That's what a database does, with a lot of overhead.
But, there's a drawback, indeed: it's f**king slow to parse/analyze.

Although you may see the following page: http://www.labsmedia.com/clickheat/156894.html (I will move it to dugwood.com one day).

If you want performance, you need to avoid loading PHP at all. That's what the last point does. The main issue with ClickHeat is that it has to work on every custom installation. Else it would be 10 to 100 times faster. But that would mean hosting it, and that's a way I didn't want to follow :-)

**Comment by selfnavi** [comment]
Thanks for the suggestion. You are absolutely right.
I threw negative texts, and set a new explanation. Look at this link: https://github.com/piwikjapan/plugin-clickheat 
I put a screenshot, everything's ready.

**Pull request merged**
